# Generated by Django 4.1.4 on 2022-12-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slideimg',
            field=models.FileField(blank=True, upload_to='slide/'),
        ),
    ]
